commands = {
    ("what","where","when","who","?","?","?","what","where","when","who","?","?","?"): "question",
    ("time", "time","time is it now", "what is the time", "what is the time", "what is the time", "time please", "current time"): "time_now",
    ("wikipedia", "i need to search on wikipedia", "could you search on wikipedia", "search wikipedia please" ,"i want to look something up on wikipedia") : "wikipedia",
    ("play on youtube", "play something on youtube", "youtube please"): "youtube",
    ("search on google", "google search","search on google", "google search","search on google", "google search"): "google",
    ("check the internet speed", "test internet speed", "internet speed check"): "internet_speed",
    ("close the application", "quit the app","close the application", "quit the app","close the application", "quit the app"): "close",
    ("temperature in the city", "what's the temperature","temperature in the city", "what's the temperature","temperature in the city", "what's the temperature"): "temperature",
    ("weather", "current weather conditions","weather", "current weather conditions","weather", "current weather conditions"): "weather",
    ("photo","take photo","take a photo","take a photo", "take a picture", "camera open","open camera"): "camera",
    ("latest news", "news updates"): "news",
    ("increase volume", "turn up the volume", "raise the volume","volume up","volume up","volume up"): "volume_up",
    ("decrease volume", "turn down the volume", "lower the volume","volume down","volume down","volume down"): "volume_down",
    ("mute sound", "mute audio", "silence","mute sound", "mute audio", "silence","mute sound", "mute audio", "silence"): "mute",
    ("start playing", "resume playback", "continue","start playing", "resume playback", "continue","start playing", "resume playback", "continue"): "play",
    ("pause playback", "stop playing"): "pause",
    ("open website", "navigate to website", "go to website"): "open_website",
    ("take screenshot","take screenshot","take screenshot","take screenshot", "capture screen", "screen grab"): "take_screenshot",
    ("shutdown", "turn off computer","shutdown", "turn off computer","shutdown", "turn off computer"): "shutdown",
    ("restart", "reboot system","restart", "reboot system","restart", "reboot system","restart", "reboot system"): "restart",
    ("sleep mode", "put computer to sleep","sleep mode", "put computer to sleep","sleep mode", "put computer to sleep","sleep computer"): "sleep_mode",
    ("open folder", "explore directory", "navigate to folder","open folder", "explore directory", "navigate to folder"): "open_folder",
    ("create folder", "make directory", "new folder"): "create_folder",
    ("lock computer", "secure system","lock computer", "secure system","lock computer", "secure system"): "lock_computer",
    ("empty recyclebin", "clear recycle bin", "delete trash","empty recyclebin", "clear recycle bin", "delete trash","empty recyclebin", "clear recycle bin", "delete trash"): "empty_recycle_bin",
    ("system uptime", "how long system has been running", "uptime","system uptime", "how long system has been running", "uptime","system uptime", "how long system has been running", "uptime"): "get_system_uptime_hours",
    ("system information", "specs", "computer details","system information", "specs", "computer details","system information", "specs", "computer details"): "get_system_information",
    ("process list", "running programs", "current processes","process list", "running programs", "current processes","process list", "running programs", "current processes"): "get_process_list",
    ("battery info", "power status", "battery details","battery info", "power status", "battery details","battery info", "power status", "battery details"): "get_battery_info",
    ("switch between windows", "change active window", "switch application","switch between windows", "change active window", "switch application","switch between windows", "change active window", "switch application"): "switch_between_windows",
    ("minimize window", "hide window", "reduce window size","minimize window", "hide window", "reduce window size","minimize window", "hide window", "reduce window size"): "minimize_window",
    ("maximize window", "expand window", "enlarge window","maximize window", "expand window", "enlarge window","maximize window", "expand window", "enlarge window"): "maximize_window",
    ("close window", "close the window", "close this window","close window", "close the window", "close this window","close window", "close the window", "close this window"): "close_window",
    ("refresh", "refresh screen", "reload","refresh", "refresh screen", "reload","refresh", "refresh screen", "reload"): "refresh",
    ("restore down", "restore window down", "minimize and resize"): "restore_down",
    ("move window left", "shift window left"): "move_window_left",
    ("move window right", "shift window right"): "move_window_right",
    ("switch to next window", "next window", "move to next window"): "switch_to_next_window",
    ("switch to previous window", "previous window", "move to previous window"): "switch_to_previous_window",
    ("open task manager", "launch task manager", "start task manager"): "open_task_manager",
    ("lock screen", "lock workstation", "lock computer screen","lock screen", "lock workstation", "lock computer screen","lock the computer"): "lock_screen",
    ("switch virtual desktop left", "move to left virtual desktop", "go to left desktop"): "switch_virtual_desktop_left",
    ("switch virtual desktop right", "move to right virtual desktop", "go to right desktop"): "switch_virtual_desktop_right",
    ("minimize all windows", "minimize every window", "show desktop"): "minimize_all_windows",
    ("show desktop", "show all windows"): "show_desktop",
    ("open file explorer", "launch file explorer", "start file explorer"): "open_file_explorer",
    ("toggle full screen mode", "switch to full screen", "enter full screen"): "toggle_full_screen_mode",
    ("open run dialog", "launch run dialog", "start run dialog"): "open_run_dialog",
    ("open action center", "launch action center", "start action center"): "open_action_center",
    ("open settings", "launch settings", "start settings"): "open_settings",
    ("open task view", "launch task view", "start task view"): "open_task_view",
    ("open notification center", "launch notification center", "start notification center"): "open_notification_center",
    ("open clipboard history", "launch clipboard history", "start clipboard history"): "open_clipboard_history",
    ("open snipping tool", "launch snipping tool", "start snipping tool"): "open_snipping_tool",
    ("open magnifier", "launch magnifier", "start magnifier"): "open_magnifier",
    ("open narrator", "launch narrator", "start narrator"): "open_narrator",
    ("open on-screen keyboard", "launch on-screen keyboard", "start on-screen keyboard"): "open_on_screen_keyboard",
    ("open ease of access center", "launch ease of access center", "start ease of access center"): "open_ease_of_access_center",
    ("open high contrast settings", "launch high contrast settings", "start high contrast settings"): "open_high_contrast_settings",
    ("open control panel", "launch control panel", "start control panel"): "open_control_panel",
    ("open device manager", "launch device manager", "start device manager"): "open_device_manager",
    ("open disk management", "launch disk management", "start disk management"): "open_disk_management",
    ("open event viewer", "launch event viewer", "start event viewer"): "open_event_viewer",
    ("open performance monitor", "launch performance monitor", "start performance monitor"): "open_performance_monitor",
    ("open power options", "launch power options", "start power options"): "open_power_options",
    ("open programs and features", "launch programs and features", "start programs and features"): "open_programs_and_features",
    ("open system information", "launch system information", "start system information"): "open_system_information",
    ("open task scheduler", "launch task scheduler", "start task scheduler"): "open_task_scheduler",
    ("open disk cleanup", "launch disk cleanup", "start disk cleanup"): "open_disk_cleanup",
    ("open remote desktop connection", "launch remote desktop connection", "start remote desktop connection"): "open_remote_desktop_connection",
    ("open services", "launch services", "start services"): "open_services",
    ("open system configuration", "launch system configuration", "start system configuration"): "open_system_configuration",
    ("open registry editor", "launch registry editor", "start registry editor"): "open_registry_editor",
    ("open windows security", "launch windows security", "start windows security"): "open_windows_security",
    ("open resource monitor", "launch resource monitor", "start resource monitor"): "open_resource_monitor",
    ("open command prompt as admin", "launch command prompt as admin", "start command prompt as admin"): "open_command_prompt_as_admin",
    ("open taskbar settings", "launch taskbar settings", "start taskbar settings"): "open_taskbar_settings",
    ("open system settings", "launch system settings", "start system settings"): "open_system_settings",
    ("open network settings", "launch network settings", "start network settings"): "open_network_settings",
    ("open personalization settings", "launch personalization settings", "start personalization settings"): "open_personalization_settings",
    ("open time and language settings", "launch time and language settings", "start time and language settings"): "open_time_and_language_settings",
    ("open privacy settings", "launch privacy settings", "start privacy settings"): "open_privacy_settings",
    ("open update and security settings", "launch update and security settings", "start update and security settings"): "open_update_and_security_settings",
    ("open ease of access settings", "launch ease of access settings", "start ease of access settings"): "open_ease_of_access_settings",
    ("open devices settings", "launch devices settings", "start devices settings"): "open_devices_settings",
    ("open phone settings", "launch phone settings", "start phone settings"): "open_phone_settings",
    ("open apps settings", "launch apps settings", "start apps settings"): "open_apps_settings",
    ("open account settings", "launch account settings", "start account settings"): "open_account_settings",
    ("open powershell", "launch powershell", "start powershell"): "open_powershell",
    ("open calculator", "launch calculator", "start calculator"): "open_calculator",
    ("open notepad", "launch notepad", "start notepad"): "open_notepad",
    ("open paint", "launch paint", "start paint"): "open_paint",
    ("open wordpad", "launch wordpad", "start wordpad"): "open_wordpad",
    ("open system properties", "launch system properties", "start system properties"): "open_system_properties",
    ("open user accounts", "launch user accounts", "start user accounts"): "open_user_accounts",
    ("open network connections", "launch network connections", "start network connections"): "open_network_connections",
    ("open system restore", "launch system restore", "start system restore"): "open_system_restore",
    ("open computer management", "launch computer management", "start computer management"): "open_computer_management",
    ("open firewall settings", "launch firewall settings", "start firewall settings"): "open_firewall_settings",
    ("open display settings", "launch display settings", "start display settings"): "open_display_settings",
    ("open sound settings", "launch sound settings", "start sound settings"): "open_sound_settings",
    ("open date and time settings", "launch date and time settings", "start date and time settings"): "open_date_and_time_settings",
    ("open default apps", "launch default apps", "start default apps"): "open_default_apps",
    ("turn on wifi", "enable wifi", "activate wifi"): "turn_on_wifi",
    ("turn off wifi", "disable wifi", "deactivate wifi"): "turn_off_wifi",
    ("turn on darkmode", "enable dark mode", "activate dark mode"): "turn_on_darkmode",
    ("turn off darkmode", "disable dark mode", "deactivate dark mode"): "turn_off_darkmode",
    ("brightness to", "set brightness to","brightness to", "set brightness to","brightness to", "set brightness to"): "set_display_brightness",
    ("increase brightness", "raise brightness", "brighten display","increase brightness", "raise brightness", "brighten display","increase brightness", "raise brightness", "brighten display"): "increase_display_brightness",   
    ("decrease brightness", "lower brightness", "dim display","decrease brightness", "lower brightness", "dim display","decrease brightness", "lower brightness", "dim display"): "decrease_display_brightness",
    ("open", "launch", "start","open", "launch", "start","open", "launch", "start"): "openCommand3",
}